const { chromium } = require('../../tools/qalab-runner/eval/node_modules/playwright');
const assert = require('node:assert/strict');
(async () => {
  const browser = await chromium.launch({ headless: true });
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
    const writes = [], errors = [];
    let failReview = false, failHistory = false, evalPending = false;
    let failExtract = false;
    let testJobStatus = 'done';
    let cancelStatus = 500;
    const queries = Array.from({ length: 40 }, (_, i) => ({ id: i + 1, title: `测评用例 ${i + 1}`, dimension: 'thinking', prompt: '完整提问\n'.repeat(15) + '提问结尾', expected: '完整预期\n'.repeat(15) + '预期结尾', conversation_group: '对话组', turn_index: i + 1 }));
    page.on('pageerror', error => errors.push(error.message));
    await page.addInitScript(() => localStorage.setItem('tp_token', 'mock-local-only'));
    await page.route(url => url.pathname.startsWith('/api/'), async route => {
      const request = route.request(), path = new URL(request.url()).pathname;
      if (request.method() !== 'GET') writes.push({ path, body: request.headers()['content-type']?.includes('multipart/form-data') ? request.postData() : request.postDataJSON() });
      let data = [];
      if (path.endsWith('/auth/me')) data = { user: { id: 1, name: '测试员' }, is_platform_admin: true, memberships: [] };
      if (path.endsWith('/projects')) data = [{ id: 1, name: '测试项目' }];
      if (path === '/api/tasks') data = [{ id: 2, title: '功能测试任务', status: 'pending' }];
      if (path.endsWith('/ai/extract-url')) {
        if (failExtract) return route.fulfill({ status: 500, json: { msg: '模拟提取失败' } });
        data = { text: '链接需求正文', title: '链接需求', chars: 6 };
      }
      if (path.endsWith('/ai/extract-file')) data = { text: '文件需求正文', filename: 'requirement.txt', chars: 6 };
      if (path.endsWith('/ai/status')) data = { available: true, default: 'deepseek', providers: [{ id: 'deepseek', available: true }, { id: 'claude', available: true }] };
      if (path.endsWith('/ai/eval-dimensions')) data = { dimensions: [{ key: 'thinking', label: '思考推理' }] };
      if (path.endsWith('/eval-tasks')) data = [{ id: 8, name: '关联任务' }];
      if (path.endsWith('/devices')) data = [{ runner_id: 'runner-1', name: '本地模拟机' }];
      if (path.endsWith('/eval-devices')) data = [{ vm_id: 'vm-1', name: '目标设备', status: 'online' }];
      if (path.endsWith('/ai/eval-queries')) data = { job_id: 1 };
      if (path === '/api/ai/testcases') data = { job_id: 2 };
      if (path.endsWith('/ai-jobs/2')) data = { id: 2, status: testJobStatus, error: '模拟生成失败', result: { cases: [{ id: 61, title: '新生成测试点', steps: '执行步骤', expected: '结果正确' }], case_count: 1 } };
      if (path.endsWith('/ai-jobs/2/cancel')) return route.fulfill({ status: cancelStatus, json: cancelStatus === 200 ? { code: 0, data: {} } : { msg: '模拟取消失败' } });
      if (path.endsWith('/ai-jobs/1')) data = evalPending ? { id: 1, status: 'pending' } : { status: 'done', result: { queries, case_count: 40, duration_ms: 1200 } };
      if (path.endsWith('/ai/tasks')) data = [{ id: 10, created_at: '2026-09-10T10:00:00', case_count: 1, status: 'done' }];
      if (path.endsWith('/ai/tasks/10/cases')) {
        if (failHistory) return route.fulfill({ status: 500, json: { msg: '模拟历史加载失败' } });
        data = [{ id: 60, title: '历史测试点', steps: '步骤\n'.repeat(20) + '步骤结尾', expected: '预期\n'.repeat(20) + '结果结尾', review_status: 'pending' }];
      }
      if (path.endsWith('/ai/testcases/60')) {
        if (failReview) return route.fulfill({ status: 500, json: { msg: '模拟评审失败' } });
        data = { review_status: request.postDataJSON().review_status, adopted: request.postDataJSON().review_status === 'adopted' };
      }
      if (path.endsWith('/eval-queue/enqueue')) data = { run_ids: [1], batch_id: 'mock' };
      await route.fulfill({ json: { code: 0, data } });
    });
    await page.goto(`${process.env.UI_BASE_URL || 'http://127.0.0.1:5189'}/ai-eval-gen`);
    await page.getByText('关联测评任务（可选）', { exact: true }).click();
    await page.getByRole('option', { name: '关联任务', exact: true }).click();
    await page.locator('textarea').fill('测评需求');
    await page.getByRole('button', { name: '生成测评 query', exact: true }).click();
    await page.getByRole('button', { name: '测评用例 1', exact: true }).waitFor();
    assert.deepEqual(writes.find(w => w.path.endsWith('/ai/eval-queries')).body, { project_id: 1, eval_task_id: 8, input_type: 'text', provider: 'deepseek', requirement: '测评需求', dimensions: ['thinking'] });
    await page.locator('.el-table__body-wrapper tbody tr').first().locator('.el-checkbox').click();
    await page.getByText('生成配置', { exact: true }).click();
    assert.equal(await page.locator('textarea').inputValue(), '测评需求');
    await page.getByText('生成结果（40）', { exact: true }).click();
    await page.getByText('已选 1 条', { exact: true }).waitFor();
    await page.getByRole('button', { name: '测评用例 1', exact: true }).click();
    assert.match(await page.locator('.el-drawer').innerText(), /提问结尾/);
    assert.match(await page.locator('.el-drawer').innerText(), /预期结尾/);
    await page.locator('.el-drawer__close-btn').click();
    await page.locator('.el-drawer').waitFor({ state: 'hidden' });
    await page.getByRole('button', { name: '测评用例 40', exact: true }).scrollIntoViewIfNeeded();
    const toolbar = await page.locator('.workspace-toolbar').boundingBox();
    assert(toolbar.y >= 50 && toolbar.y < 100);
    await page.getByRole('button', { name: '发送到执行机', exact: true }).click();
    await page.getByRole('button', { name: '取消', exact: true }).click();
    assert(!writes.some(w => w.path.endsWith('/eval-queue/enqueue')));
    await page.setViewportSize({ width: 390, height: 844 });
    await page.getByRole('button', { name: '收起侧栏' }).click();
    await page.getByRole('button', { name: '发送到执行机', exact: true }).click();
    const dialog = page.locator('.el-dialog');
    await dialog.getByText('选目标设备(可空)', { exact: true }).click();
    await page.getByRole('option', { name: /目标设备/ }).click();
    await page.getByRole('option', { name: /目标设备/ }).waitFor({ state: 'hidden' });
    await page.screenshot({ path: '/tmp/generation-dispatch-mobile.png' });
    const box = await dialog.boundingBox();
    assert(box.x >= 0 && box.x + box.width <= 390);
    await dialog.getByRole('button', { name: '确认下发', exact: true }).click();
    await dialog.waitFor({ state: 'hidden' });
    assert.deepEqual(writes.find(w => w.path.endsWith('/eval-queue/enqueue')).body, { project_id: 1, runner: 'runner-1', target_engine: 'namiwork', target_device: 'vm-1', eval_query_ids: [1] });
    await page.getByText('生成配置', { exact: true }).click();
    evalPending = true;
    await page.getByRole('button', { name: '生成测评 query', exact: true }).click();
    await page.getByRole('button', { name: '停止等待', exact: true }).click();
    await page.getByRole('button', { name: '生成测评 query', exact: true }).waitFor();
    await page.getByText('已停止等待，后台生成任务可能仍在执行；完成后可在测评用例库查看', { exact: true }).waitFor();
    assert(!writes.some(write => write.path.endsWith('/cancel')));
    evalPending = false;
    await page.waitForTimeout(2200);
    assert.equal(await page.getByRole('button', { name: '测评用例 1', exact: true }).count(), 0);
    await page.goto(`${process.env.UI_BASE_URL || 'http://127.0.0.1:5189'}/ai-testgen`);
    failHistory = true;
    await page.getByText('查看历史生成', { exact: true }).click();
    await page.getByRole('option', { name: /#10/ }).click();
    await page.getByText('历史生成记录加载失败', { exact: true }).waitFor();
    assert.equal(await page.getByRole('button', { name: '历史测试点', exact: true }).count(), 0);
    failHistory = false;
    await page.getByRole('button', { name: '重新加载', exact: true }).click();
    await page.getByRole('button', { name: '历史测试点', exact: true }).click();
    const drawer = page.locator('.el-drawer');
    await drawer.waitFor();
    assert.match(await drawer.innerText(), /步骤结尾/);
    assert.match(await drawer.innerText(), /结果结尾/);
    failReview = true;
    await drawer.getByText('采纳', { exact: true }).click();
    await page.getByText('操作失败，请重试', { exact: true }).waitFor();
    assert.equal(await drawer.getByRole('radio', { name: '待定', exact: true }).isChecked(), true);
    failReview = false;
    const reviewResponse = page.waitForResponse(response => response.url().endsWith('/ai/testcases/60'));
    await drawer.getByText('采纳', { exact: true }).click();
    await reviewResponse;
    await page.waitForFunction(() => document.querySelector('.el-drawer input[value="adopted"]')?.checked);
    await page.waitForTimeout(350);
    assert.deepEqual(writes.find(w => w.path.endsWith('/ai/testcases/60')).body, { review_status: 'adopted' });
    await page.screenshot({ path: '/tmp/generation-review-mobile.png' });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
    await drawer.locator('.el-drawer__close-btn').click();
    await drawer.waitFor({ state: 'hidden' });
    await page.getByText('生成配置', { exact: true }).click();
    await page.locator('.el-select').filter({ hasText: '关联任务（必填）' }).getByRole('combobox').click();
    await page.getByRole('option', { name: /功能测试任务/ }).click();
    await page.getByText('编辑', { exact: true }).click();
    await page.locator('textarea').fill('功能需求');
    await page.locator('.scenario-only').click();
    await page.getByRole('button', { name: '生成测试点', exact: true }).click();
    await page.getByRole('button', { name: '新生成测试点', exact: true }).waitFor();
    assert.deepEqual(writes.find(w => w.path === '/api/ai/testcases').body, { project_id: 1, task_id: 2, input_type: 'text', provider: 'deepseek', requirement: '功能需求', scenario_only: true });
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.getByRole('button', { name: '展开侧栏' }).click();
    await page.waitForTimeout(350);
    await page.screenshot({ path: '/tmp/generation-results-desktop.png' });
    await page.getByText('生成配置', { exact: true }).click();
    await page.getByRole('button', { name: '需求链接', exact: true }).click();
    await page.getByPlaceholder('需求网页链接，或飞书 docx/wiki/sheets/base 链接').fill('https://example.com/requirement');
    failExtract = true;
    await page.getByRole('button', { name: '抓取正文', exact: true }).click();
    await page.getByText('模拟提取失败', { exact: true }).waitFor();
    assert.equal(await page.locator('textarea').inputValue(), '功能需求');
    failExtract = false;
    await page.getByRole('button', { name: '抓取正文', exact: true }).click();
    await page.getByText('链接需求正文', { exact: true }).waitFor();
    assert.deepEqual(writes.find(write => write.path.endsWith('/ai/extract-url')).body, { url: 'https://example.com/requirement' });
    await page.getByRole('button', { name: '上传文档', exact: true }).click();
    await page.locator('input[type="file"]').setInputFiles({ name: 'requirement.txt', mimeType: 'text/plain', buffer: Buffer.from('文件需求正文') });
    await page.getByText('文件需求正文', { exact: true }).waitFor();
    await page.getByRole('button', { name: '生成测试点', exact: true }).click();
    await page.getByRole('button', { name: '新生成测试点', exact: true }).waitFor();
    const filePayload = writes.filter(write => write.path === '/api/ai/testcases').at(-1).body;
    assert.equal(filePayload.input_type, 'file');
    assert.equal(filePayload.requirement, '文件需求正文');
    assert.equal(filePayload.requirement_title, 'requirement.txt');
    assert.equal(filePayload.requirement_url, undefined);
    await page.getByText('生成配置', { exact: true }).click();
    testJobStatus = 'failed';
    await page.getByRole('button', { name: '生成测试点', exact: true }).click();
    await page.getByText('模拟生成失败', { exact: true }).waitFor();
    assert.equal(await page.getByRole('button', { name: '新生成测试点', exact: true }).count(), 0);
    await page.getByText('文件需求正文', { exact: true }).waitFor();
    testJobStatus = 'pending';
    await page.getByRole('button', { name: '生成测试点', exact: true }).click();
    await page.getByText('排队中', { exact: true }).waitFor();
    await page.getByRole('button', { name: '取消', exact: true }).click();
    await page.getByText('取消请求未成功，已停止等待；后台任务状态尚未确认，请稍后查看历史记录', { exact: true }).waitFor();
    await page.getByRole('button', { name: '生成测试点', exact: true }).waitFor();
    assert(writes.some(write => write.path === '/api/ai-jobs/2/cancel'));
    for (const [status, jobState, message] of [[200, 'pending', '已取消排队任务，队列位已释放'], [409, 'running', '任务执行中无法中断，已停止等待（后台仍会完成，可稍后在历史中查看）']]) {
      cancelStatus = status;
      testJobStatus = jobState;
      await page.getByRole('button', { name: '生成测试点', exact: true }).click();
      await page.getByText(jobState === 'pending' ? '排队中' : '执行中', { exact: true }).waitFor();
      assert.equal(await page.locator('.form-row .el-select').first().getByRole('combobox').isDisabled(), true);
      await page.getByRole('button', { name: '取消', exact: true }).click();
      await page.getByText(message, { exact: true }).waitFor();
      await page.getByRole('button', { name: '生成测试点', exact: true }).waitFor();
    }
    assert.deepEqual(errors, []);
    console.log('PASS generation payloads, selection, details, mobile dispatch, history/review failures, extraction sources, generation failure and cancellation uncertainty');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exit(1); });
