"""集中注册所有路由。"""
from fastapi import APIRouter

from app.api import auth, issues, members, projects, reports, stats, tasks, tools, users, ai, checklist, exec_queue, devices, release, selectors, probe, api_env, perf, ai_eval, eval_queue, eval_judge, eval_export, eval_devices, eval_task, feedback, release_checklist, runner_update, test_plan, hooks

api_router = APIRouter()
api_router.include_router(auth.router)
api_router.include_router(projects.router)
api_router.include_router(members.router)
api_router.include_router(users.router)
api_router.include_router(tasks.router)
api_router.include_router(reports.router)
api_router.include_router(stats.router)
api_router.include_router(issues.router)
api_router.include_router(tools.router)
api_router.include_router(ai.router)
api_router.include_router(ai_eval.router)
api_router.include_router(eval_queue.router)
api_router.include_router(eval_judge.router)
api_router.include_router(eval_export.router)
api_router.include_router(eval_devices.router)
api_router.include_router(eval_task.router)
api_router.include_router(checklist.router)
api_router.include_router(exec_queue.router)
api_router.include_router(devices.router)
api_router.include_router(release.router)
api_router.include_router(selectors.router)
api_router.include_router(probe.router)
api_router.include_router(api_env.router)
api_router.include_router(perf.router)
api_router.include_router(feedback.router)
api_router.include_router(release_checklist.router)
api_router.include_router(runner_update.router)
api_router.include_router(test_plan.router)
api_router.include_router(hooks.router)
